name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: install backend
        run: npm install
      - name: install frontend
        run: cd frontend && npm i
      - name: build
        run: cd frontend && npm run build
      - name: lint
        run: npm run lint & ls -la
      - name: heroku deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        if: ${{ github.event_name == 'push' }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tranquil-arches-00913"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://tranquil-arches-00913.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
